import './Disclaimer.css';

/**
 * Persistent educational-use disclaimer.
 * MedIntel AI is a student project — never a certified diagnostic tool.
 * Shown across every page so the caveat is never more than one screen away.
 */
export default function Disclaimer() {
  return (
    <footer className="disclaimer">
      <span className="disclaimer-icon">i</span>
      <p>
        MedIntel AI is an educational demo, not a certified medical diagnosis
        tool. Predictions are generated by a machine learning model and can be
        wrong — always consult a licensed clinician about your health.
      </p>
    </footer>
  );
}
